### ISSUE TITLE
Mamba 130m fine-tuning recipe

### ISSUE THREAD

**Issue by johnhalloran321** [booydar/babilong#9]
Hi,

Is the Mamba 130M fine-tuning recipe from the paper available somewhere?

Thanks in advance,
John

**Comment by RodkinIvan** [comment]
Hello, John

Yes, you can find the fine-tuning script here:
https://github.com/RodkinIvan/associative-recurrent-memory-transformer/blob/experimental/scripts/babilong/finetune_babilong_mamba.sh

We used the huggingface model

@johnhalloran321

**Comment by johnhalloran321** [comment]
Perfect, thanks Ivan!
